# Generated by Django 5.0.6 on 2024-06-17 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesh_id', models.CharField(max_length=50, unique=True)),
                ('term', models.CharField(max_length=255)),
                ('definition', models.TextField()),
                ('entry_date', models.DateTimeField()),
                ('date_revised', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_ui', models.CharField(max_length=100)),
                ('concept_name', models.CharField(max_length=255)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='medicalapp.medicalrecord')),
            ],
        ),
        migrations.CreateModel(
            name='AllowableQualifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualifier_name', models.CharField(max_length=255)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowable_qualifiers', to='medicalapp.medicalrecord')),
            ],
        ),
        migrations.CreateModel(
            name='PharmacologicalAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(max_length=255)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacological_actions', to='medicalapp.medicalrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonym', models.CharField(max_length=255)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='medicalapp.medicalrecord')),
            ],
        ),
        migrations.CreateModel(
            name='TreeNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_number', models.CharField(max_length=100)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tree_numbers', to='medicalapp.medicalrecord')),
            ],
        ),
    ]
