# Generated by Django 5.0.6 on 2024-06-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='date_revised',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
